### ISSUE TITLE
Erreur sur lien 'en savoir plus' sur fiche lieu émergence

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#135]
Hello @baptadn 

Le lien ne part pas de la racine et du coup il ne renvoie pas vers le bon contenu.

![Capture d’écran 2024-05-02 à 10 47 35](https://github.com/AtelierdeParis/studio-d/assets/764332/9c27e1df-b675-4505-a3aa-a1244b4bd3de)

Repro: Aller sur [n'importe quelle page d'espace en mode émergence](https://www.studiod-danse.fr/espaces/theatre-de-vanves-salle-panopee?tab=1) et cliquer sur 'en savoir plus'.

**Comment by baptadn** [comment]
Corrigé en prod

**Comment by ImaCrea** [comment]
merci
