### ISSUE TITLE
Les disponibilités de créneaux de campagne s'affichent en indication dans les cartes des lieux sur la page Espace alors qu'on en mode créneaux solidaires

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#140]
Sur la home on est OK. 

Souci côté grille des espaces. Ces label ne devraient pas s'afficher dans les cartes puisqu'on est en mode de navigation créneaux solidaires :

![bug](https://github.com/user-attachments/assets/adfcb8a0-16f7-4efc-b236-55c6c7861586)

**Comment by baptadn** [comment]
@ImaCrea c'est corrigé et déployé en prod, je te laisse vérifier ?

**Comment by ImaCrea** [comment]
looking good :)
