### ISSUE TITLE
Les disponibilités de créneaux solidaires ne s'affichent pas dans les cartes des lieux sur la page espace alors qu'on est en mode créneaux solidaires

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#141]
corollaire de #140 - toujours page des epaces
on dirait qu'il y a eu une inversion sur la condition quand on est hors campagne et donc en mode créneaux solidaire par défaut.

![bug](https://github.com/user-attachments/assets/884d4f45-2d75-4c72-8b14-2fa4010d9ecc)

**Comment by baptadn** [comment]
@ImaCrea, c’est normal qu’aucun badge ne s’affiche dans ce cas, car ils ne sont visibles que si les disponibilités sont dans la semaine en cours ou la suivante.
