### ISSUE TITLE
Erreurs d'affichages sur créneaux pour Karukera Ballet

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#142]
Plus étrange ici.

Ces créneaux ne semblent pas être de type campagne, pourtant le lieu n'est pas affiché sur la home. Mais, le label dans sa carte sur la page espace indiquent bien des créneaux (contrairement à ce qui observé pour #141 ) par contre l'affichage des créneaux sur la page de l'espace est cassé. Comme s'ils étaient arrivés à créer des créneaux qui ne devraient pas exister, on ne devrait pas avoir ce type de chevauchement possible.

![bug](https://github.com/user-attachments/assets/5cde6b28-5fc1-4a88-822a-205de0db31f4)

**Comment by baptadn** [comment]
@ImaCrea corrigé (problème de timezone)

**Comment by ImaCrea** [comment]
Vu, bien joué. Merci !
