### ISSUE TITLE
Revoir la compression des thumbnails des actus en home

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#144]
La compression est jugée trop forte par Atelier de Paris. En effet l'image pixellise pas mal.

![image001-1](https://github.com/user-attachments/assets/19df2182-c033-4b10-9e8d-450561e152ff)

Il serait bon de revoir le réglage pour un affichage moins pixellisé, tout en essayant de garder une taille d'image raisonnable pour des raisons d'écoconception. En l'état on a des images de 156 × 156 pixels et de 5kb. On a de la marge :)

**Comment by baptadn** [comment]
@ImaCrea j'ai changé pour la vignette "large" de Strapi (en mode tablette, on peut avoir des images assez larges)

**Comment by ImaCrea** [comment]
top, merci!
