### ISSUE TITLE
Faut-il prévoir une mise à jour imminente ?

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#145]
DigitalOcean va forcer la mise à jour de la DB vers PostgreSQL 16 le **14 novembre**.
Actuellement l'instance Strapi est sous version 3.6.8. Est-ce qu'elle pourra supporter ce changement ? (Je n'ai rien trouvé dans la doc de Strapi v3 à ce propos.)

Par ailleurs on est sous Node 14.21.3 qui n'est plus maintenu. et Strapi 5 arrive...

Pour assurer la bonne qualité de service de StudioD, éviter des interruptions et faciliter le développement de futures évolutions, ne serait-il pas nécessaire de prévoir une mise à jour du système sous peu ? Quel délai recommandé ? Quelle estimation pour cette opération de maintenance ?

**Comment by baptadn** [comment]
@ImaCrea la mise à jour vers pgsql 16 a été faite

**Comment by ImaCrea** [comment]
Discuté ensemble hier, peut encore attendre mais pourrait être bon à prévoir en vue de prochains développement. À noter que le passage de Strapi 3 à 4 se présente comme une tâche conséquente du fait des nombreux changement introduits dans cette nouvelle version. En l'état, la mise à jour de la DB ayant été faite, je ferme ce ticket.
