### ISSUE TITLE
Impossible d'écrire à plusieurs compagnies en tant que lieu

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#34]
Hier j’ai voulu envoyer un message à trois compagnies différentes qui m’avaient contactée mais les trois messages se sont envoyés à la même personne.  Comme tu peux le voir sur la photo, quand je me plaçais par exemple sur la conversation avec La Compagnie Luna et que je faisais partir le message, il s’envoyait quand même à la Cie Le Makila. 
Ca donne ça : 

![capture](https://user-images.githubusercontent.com/764332/121506194-cbddc500-c9e3-11eb-9f38-46d99b4fb7de.png)

**Comment by keery** [comment]
Je n'ai pas réussi à reproduire le même comportement, ce que j'ai fait:
- En tant que lieu, j'ai créé 2 espaces avec des créneaux
- Avec 2 comptes compagnie différents j'ai fait une résa sur le premier espace, et avec le deuxième compte sur le deuxième espace
- Je suis retourné sur le compte lieu dans la messagerie, envoyé un message au premier, puis au deuxième, aucun message n'était dupliqué

J'ai répété le même procédé mais cette fois ci avec deux compagnies qui font des demandes pour le même espace, mais pas de problème non plus.

**Comment by ImaCrea** [comment]
Merci @keery d'avoir tenté de le reproduire. Peut-être que @ClaireKoch peut nous en dire plus pour nous aiguiller et nous permettre de mieux comprendre ce qui s'est passé de son côté.

**Comment by ClaireKoch** [comment]
Nous avons refait le test et là tout s'est bien passé, ça a du être un bug ponctuel. Merci ! 
Le bug concernant la notification est parti aussi.

**Comment by ImaCrea** [comment]
Bien, merci ! Je ferme ce ticket.
