### ISSUE TITLE
Souci sur l'affichage de la notif pour la section des demandes

### ISSUE THREAD

**Issue by ImaCrea** [AtelierdeParis/studio-d#35]
Quand on a des DEMANDES, une notification en orange apparaît. Quand je clique sur « demandes » cette notification disparaît mais le problème est qu’elle revient dès que je clique sur un autre onglet alors que j’ai déjà pris connaissance de ces demandes. 

https://user-images.githubusercontent.com/764332/121506505-10696080-c9e4-11eb-8e01-ad3276603384.mov

**Comment by keery** [comment]
Les notifications ne sont considérées comme ouvertes qu'à partir du moment où on ouvre le détail de la demande

**Comment by ImaCrea** [comment]
Entendu, merci pour ce retour @keery . Je comprends que ce n'est pas tellement un bug du coup mais plus une question de mauvaise compréhension de l'interface. Il me semble que les usager·ères comprendront à l'usage, ça ne me paraît donc pas prioritaire de revoir ça en l'état.

Je ferme le ticket. @ClaireKoch si tu estimes néanmoins qu'il faut revoir ce point, n'hésite pas à re-ouvrir le ticket.
